version: "3.7"
services:
  chronojudge-api:
    container_name: chronojudge-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /app/chronojudge-api
    ports:
      - 3006:3006
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    restart: always
  redis-backend:
    container_name: redis-backend
    image: "redis:alpine"
